name: cattle_monitoring
description: A Flutter app for monitoring cattle using Cubit and mock data.
publish_to: 'none'

environment:
  sdk: ^3.6.0

flutter:
  uses-material-design: true
  
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  mqtt_client: ^10.8.1
  json_annotation: ^4.8.1
  http: ^0.13.6


dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1